Add Support for http/2 in webserver tutorial
netcup-community/community-tutorials pull request #70
Opened 2021-12-22 00:43 UTC by 2020Sanoj

2021-12-22 00:50 UTC, 2020Sanoj commented
This PR adds to the tutorial how to enable http/2 in apache2

2021-12-27 14:11 UTC, raphi-0901 requested changes

2021-12-27 14:15 UTC, raphi-0901 commented
Hey, where is the screenshot for Step 1.6? There you say "see screenshot below", but there is no screenshot.

Also, in order to finish the Nextcloud installation, I had to change the nextcloud root folder´s permissions. In addition to that, when I try to visit the Nextcloud page on my server, it just keeps loading over and over.

2021-12-27 15:08 UTC, 2020Sanoj commented on community-tutorials/install-web-server-mariadb-debian-php-wordpress-yourls-nextcloud-uptimekuma/01-en.md
> -If you are doing this directly on a domain and NOT on a subdomain, I recommend repeating this step with www.DOMAIN (you can paste it in the same file, but leave some lines blank).
i replaced this line

2021-12-27 15:09 UTC, 2020Sanoj commented
> Hey, where is the screenshot for Step 1.6? There you say "see screenshot below", but there is no screenshot.

There stands nothing about a screenshot, I mean the text below

2021-12-27 15:11 UTC, 2020Sanoj commented
> Hey, where is the screenshot for Step 1.6? There you say "see screenshot below", but there is no screenshot.
> 
> Also, in order to finish the Nextcloud installation, I had to change the nextcloud root folder´s permissions. In addition to that, when I try to visit the Nextcloud page on my server, it just keeps loading over and over.

The permissions are now automatically for every file inside the folder correct and for the second did you reinstalled nextcloud or did you used an old installation?

2021-12-28 06:58 UTC, raphi-0901 commented
> > Hey, where is the screenshot for Step 1.6? There you say "see screenshot below", but there is no screenshot.
> 
> There stands nothing about a screenshot, I mean the text below

Oh  sorry, I mean Step 1.7

2021-12-28 07:00 UTC, raphi-0901 commented
> > Hey, where is the screenshot for Step 1.6? There you say "see screenshot below", but there is no screenshot.
> > Also, in order to finish the Nextcloud installation, I had to change the nextcloud root folder´s permissions. In addition to that, when I try to visit the Nextcloud page on my server, it just keeps loading over and over.
> 
> The permissions are now automatically for every file inside the folder correct and for the second did you reinstalled nextcloud or did you used an old installation?

I didn´t use an old installation.

2021-12-28 07:19 UTC, raphi-0901 commented
Ok, I reinstalled Nextcloud again and it works fine now!

2022-01-10 13:59 UTC, raphi-0901 commented
Hey @2020Sanoj, after discussion in our team we came to the decision that the tutorial is too big in size and it combines too many different topics. We would be happy if you could resubmit the tutorial in smaller parts. For example, one for Wordpress, one for Nextcloud, ... .

2022-01-10 13:59 UTC, closed without merging

2022-01-12 21:12 UTC, 2020Sanoj commented
So one for the complete web and database setup and four more for WordPress, Nextcloud, YOURLS and uptime Kama?